---
title: "hw4-wenqi"
output: html_document
---

# Q10

* Q4 is the picture

## a

```{r}
library(ISLR)
```


```{r}
summary(Weekly)
```

## b

```{r}
fit <- glm(Direction ~ Lag1+Lag2+Lag3+Lag4+Lag5+Volume,family = binomial,data = Weekly)
```

## c

```{r}
prid <- predict(fit, type = "response")
prid_glm <- ifelse(prid>0.5,"up","down")
table(prid_glm,Weekly$Direction)
```


## d

```{r}
train_data <- (Weekly$Year <= 2008)
wek <- Weekly[!train_data, ]
dir <- Weekly$Direction[!train_data]
fit_glm_lg2 <- glm(Direction ~ Lag2, data = Weekly, family = binomial, subset = train_data)
summary(fit_glm_lg2)


pred_glm_lg2 <- predict(fit_glm_lg2, wek, type = "response")
pred_glm_lg2 <- ifelse(pred_glm_lg2>0.5,"up","down")
table(pred_glm_lg2 , dir)
```


## e


```{r}
library(MASS)
fit_lda <- lda(Direction ~ Lag2, data = Weekly, subset = train_data)
prid_lda <-  predict(fit_lda, wek)
table(prid_lda$class,dir)
```

```{r}
mean(prid_lda$class == dir)
```


## f

```{r}
fit_qda <- qda(Direction ~ Lag2, data = Weekly, subset = train_data)
prid_qda <- predict(fit_qda,wek)
table(prid_qda$class,dir)
```

```{r}
mean(prid_qda$class==dir)
```


## g

```{r}
library(class)
train_knn <- as.matrix(Weekly$Lag2[train_data])
test_knn <- as.matrix(Weekly$Lag2[!train_data])
train.Direction <- Weekly$Direction[train_data]
set.seed(999)
pred.knn <- knn(train_knn, test_knn, train.Direction, k = 10)
table(pred.knn,dir)
```

```{r}
mean(pred.knn==dir)
```


## i

* overall, the better model is lda whose accuracy is 0.625

```{r}
# glm lg1+lg2
fit_glm12 <- glm(Direction ~ Lag1+abs(Lag2), data = Weekly, family = binomial, subset = train_data)
summary(fit_glm12)
pred_glm12 <- predict(fit_glm12, wek, type = "response")
pred_glm12 <- ifelse(pred_glm12>0.5,"up","down")
table(pred_glm12 , dir)
```



```{r}
#lda lg1 lg2

fit_lda12 <- lda(Direction ~ Lag1+abs(Lag2), data = Weekly, subset = train_data)
prid_lda12 <-  predict(fit_lda, wek)
table(prid_lda12$class,dir)

```

```{r}
mean(prid_lda12$class==dir)
```


```{r}
pred.knn3 <- knn(train_knn, test_knn, train.Direction, k = 3)
table(pred.knn3,dir)
```

```{r}
mean(pred.knn3==dir)
```

* we could choose lda, since it has the best performance since it accuracy is 0.65.

